thm_bg="{{colors.surface.default.hex}}"
thm_fg="{{colors.surface_container.default.hex}}"
thm_cyan="{{colors.terminal_normal_cyan.default.hex}}"
thm_black="{{colors.terminal_normal_black.default.hex}}"
thm_gray="{{colors.terminal_normal_white.default.hex}}"
thm_magenta="{{colors.terminal_normal_magenta.default.hex}}"
thm_pink="{{colors.terminal_bright_magenta.default.hex}}"
thm_red="{{colors.terminal_normal_red.default.hex}}"
thm_green="{{colors.terminal_normal_green.default.hex}}"
thm_yellow="{{colors.terminal_normal_yellow.default.hex}}"
thm_blue="{{colors.terminal_normal_blue.default.hex}}"
thm_orange="{{colors.terminal_bright_yellow.default.hex}}"
thm_black4="{{colors.terminal_bright_black.default.hex}}"

set -g status-bg "${thm_bg}"
set -g message-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g message-command-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-current-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_magenta},bg=${thm_bg}](✓) #[fg=${thm_cyan},bg=${thm_bg}]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=${thm_magenta},bg=${thm_bg}]"
set -g window-status-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_fg},bg=${thm_bg}]#W"
set -g status-right "#[fg=${thm_blue},bg=${thm_bg},nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_blue},nobold,nounderscore,noitalics] #[fg=${thm_fg},bg=${thm_gray}] #W #{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_cyan}]}#[bg=${thm_gray}]#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_cyan}]}#[fg=${thm_bg}] #[fg=${thm_fg},bg=${thm_gray}] #S "
set -g status-left ""
set -g clock-mode-colour "${thm_blue}"
set -g mode-style "fg=${thm_blue} bg=${thm_black4} bold"

