# bar config
  [bar.experiment]
    auto_hide = false
    background_opacity = 1.0
    border = "outline"
    border_width = 0.0
    capsule = false
    capsule_border = "secondary"
    capsule_fill = "surface_variant"
    capsule_group = []
    capsule_opacity = 0.0
    capsule_padding = 0.0
    color = "primary"
    contact_shadow = false
    enabled = true
    font_weight = 500
    layer = "top"
    marginedge = 10
    margin_ends = 0
    padding = 15
    panel_overlap = 1
    position = "top"
    radius = 0
    radius_bottom_left = 0
    radius_bottom_right = 0
    radius_top_left = 0
    radius_top_right = 0
    reserve_space = true
    scale = 1.0
    shadow = false
    thickness = 15
    widget_spacing = 10
    # bar widgets
    start = [ "workspaces", "vertical_separator", "bracket_left","control-center","vertical_separator", "tray", "bracket_right", "media" ]
    center = [ "bracket_left", "clock", "date", "bracket_right" ]
    end = [
        "bracket_left",
        "power_profile",
        "spliter",
        "bluetooth",
        "spliter",
        "network",
        "spliter",
        "volume",
        "spliter",
        "ram",
        "spliter",
        "cpu",
        "bracket_right"
    ]


