[widget.control-center]
glyph = "navigation-filled"
type = "control-center"

[widget.workspaces]
anchor = false
display = "name"
hide_when_empty = false
labels_only_when_occupied = false
style = "minimal"
type = "workspaces"


# bar config
[bar.box]
auto_hide = false
background_opacity = 1.0
border = "outline"
border_width = 0.0
capsule = false
capsule_border = "secondary"
capsule_fill = "surface_variant"
capsule_group = []
capsule_opacity = 0.0
capsule_padding = 0.0
contact_shadow = false
enabled = true
font_family = "Terminus"
font_weight = 500
hover_highlight = false
layer = "top"
margin_edge = 5
margin_ends = 0
marginedge = 0
padding = 0
panel_overlap = 1
position = "top"
radius = 0
radius_bottom_left = 0
radius_bottom_right = 0
radius_top_left = 0
radius_top_right = 0
reserve_space = true
scale = 1.0
shadow = false
thickness = 15
widget_spacing = 10
color = "primary"
center = [ "brackets_5", "clock", "separator_4", "matrix_2", "separator_5", "date", "brackets_6" ]
end = [
    "brackets_7",
    "powerprofile_2",
    "slash_separator_2",
    "battery_3",
    "slash_separator_3",
    "wifi_2",
    "slash_separator_4",
    "volume_2",
    "slash_separator_6",
    "ram_3",
    "slash_separator_5",
    "cpu_3",
    "brackets_8"
]
start = [
    "workspaces",
    "separator",
    "brackets",
    "control-center",
    "separator_2",
    "apptray_2",
    "brackets_2",
    "media",
    "separator_3",
    "brackets_3",
    "weather_3",
    "brackets_4"
]
[bar.box.monitor.eDP-1]
enabled = true
[bar.box.monitor.HDMI-A-1]
enabled = true
