#environment
env=DBUS_SESSION_BUS_ADDRESS,unix:path=/run/user/1000/bus
#monitor
monitorrule=name:^HDMI-A-1$,width:1920,height:1080,refresh:119.879,x:1920,y:60
monitorrule=name:^eDP-1$,width:1920,height:1080,refresh:144,x:0,y:0
#performance
xwayland_persistence=1
syncobj_enable=1
no_border_when_single=0
allow_tearing=0
#workspaces
tagrule=id:1,no_hide:1,layout_name:fair
tagrule=id:2,no_hide:1,layout_name:fair
tagrule=id:3,no_hide:1,layout_name:fair
tagrule=id:4,no_hide:1,layout_name:fair
tagrule=id:5,no_hide:1,layout_name:fair
tagrule=id:6,no_hide:1,layout_name:fair
tagrule=id:7,no_hide:1,layout_name:fair
tagrule=id:8,no_hide:1,layout_name:fair
tagrule=id:9,no_hide:1,layout_name:fair
# visuals
cursor_size=24
cursor_theme=Future-dark-cursors
source=~/.config/mango/visual.conf
source=/home/kuba/.config/mango/noctalia.conf
source=/home/kuba/.config/mango/keybinds.conf

exec-once=~/.config/mango/autostart.sh
