# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#ececec"

# Title color for boxes
theme[title]="#b3b3b3"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d1d1d1"

# Background color of selected item in processes box
theme[selected_bg]="#b3b3b3"

# Foreground color of selected item in processes box
theme[selected_fg]="#1a1a1a"

# Color of inactive/disabled text
theme[inactive_fg]="#a3a3a3"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ececec"

# Cpu box outline color
theme[cpu_box]="#a3a3a3"

# Memory/disks box outline color
theme[mem_box]="#a3a3a3"

# Net up/down box outline color
theme[net_box]="#a3a3a3"

# Processes box outline color
theme[proc_box]="#a3a3a3"

# Box divider line and small boxes line color
theme[div_line]="#444444"

# Temperature graph colors
theme[temp_start]="#d1d1d1"
theme[temp_mid]="#b3b3b3"
theme[temp_end]="#d9d9d9"

# CPU graph colors
theme[cpu_start]="#d1d1d1"
theme[cpu_mid]="#b3b3b3"
theme[cpu_end]="#d9d9d9"

# Mem/Disk free meter
theme[free_start]="#d1d1d1"
theme[free_mid]=""
theme[free_end]="#999999"

# Mem/Disk cached meter
theme[cached_start]="#ececec"
theme[cached_mid]=""
theme[cached_end]="#999999"

# Mem/Disk available meter
theme[available_start]="#b3b3b3"
theme[available_mid]=""
theme[available_end]="#cccccc"

# Mem/Disk used meter
theme[used_start]="#d9d9d9"
theme[used_mid]=""
theme[used_end]="#b3b3b3"

# Download graph colors
theme[download_start]="#d1d1d1"
theme[download_mid]="#b3b3b3"
theme[download_end]="#ececec"

# Upload graph colors
theme[upload_start]="#d1d1d1"
theme[upload_mid]="#b3b3b3"
theme[upload_end]="#ececec"
