# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#f8f9fa"

# Title color for boxes
theme[title]="#adb5bd"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ced4da"

# Background color of selected item in processes box
theme[selected_bg]="#adb5bd"

# Foreground color of selected item in processes box
theme[selected_fg]="#212529"

# Color of inactive/disabled text
theme[inactive_fg]="#868e96"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#dee2e6"

# Cpu box outline color
theme[cpu_box]="#868e96"

# Memory/disks box outline color
theme[mem_box]="#868e96"

# Net up/down box outline color
theme[net_box]="#868e96"

# Processes box outline color
theme[proc_box]="#868e96"

# Box divider line and small boxes line color
theme[div_line]="#495057"

# Temperature graph colors
theme[temp_start]="#ced4da"
theme[temp_mid]="#adb5bd"
theme[temp_end]="#f7768e"

# CPU graph colors
theme[cpu_start]="#ced4da"
theme[cpu_mid]="#adb5bd"
theme[cpu_end]="#f7768e"

# Mem/Disk free meter
theme[free_start]="#ced4da"
theme[free_mid]=""
theme[free_end]="#6c757d"

# Mem/Disk cached meter
theme[cached_start]="#dee2e6"
theme[cached_mid]=""
theme[cached_end]="#6c757d"

# Mem/Disk available meter
theme[available_start]="#adb5bd"
theme[available_mid]=""
theme[available_end]="#868e96"

# Mem/Disk used meter
theme[used_start]="#f7768e"
theme[used_mid]=""
theme[used_end]="#db4b4b"

# Download graph colors
theme[download_start]="#ced4da"
theme[download_mid]="#adb5bd"
theme[download_end]="#dee2e6"

# Upload graph colors
theme[upload_start]="#ced4da"
theme[upload_mid]="#adb5bd"
theme[upload_end]="#dee2e6"
