#input
repeat_rate=35
numlockon=0
drag_tile_to_tile=1
sloppyfocus=1
xkb_rules_layout=pl
xkb_rules_options=caps2super:super
#mouse binds
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

#keybinds

#workspaces switch

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

#move window to workspace

bind=SUPER+Shift,1,tag,1,0
bind=SUPER+Shift,2,tag,2,0
bind=SUPER+Shift,3,tag,3,0
bind=SUPER+Shift,4,tag,4,0
bind=SUPER+Shift,5,tag,5,0
bind=SUPER+Shift,6,tag,6,0
bind=SUPER+Shift,7,tag,7,0
bind=SUPER+Shift,8,tag,8,0
bind=SUPER+Shift,9,tag,9,0

# Focus window in direction
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down
# Focus window in direction vim style
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down
# Move/Swap Windows in direction vim style
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right
# Move/Swap Windows in direction
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# toggle float

bind=SUPER,f,togglefloating

# Toggle maximize screen

bind=SUPER,w,togglemaximizescreen

# Toggle fullscreen

bind=SUPER+SHIFT,w,togglefullscreen
#bind=SUPER+SHIFT,w,togglefakefullscreen

#kill window

bind=SUPER,q,killclient

# reload conifguration

bind=SUPER,r,reload_config

# shell binds

bind=SUPER,a,spawn_shell,rofi --show drun
bind=SUPER,y,spawn_shell,~/.config/mango/scripts/wallpaper.sh
bind=SUPER,escape,spawn_shell,~/.config/mango/scripts/power.sh
# audio
bind=NONE,XF86AudioRaiseVolume,spawn_shell,~/.config/mango/scripts/volup.sh
bind=NONE,XF86AudioLowerVolume,spawn_shell,~/.config/mango/scripts/voldown.sh
bind=NONE,XF86AudioMute,spawn_shell,~/.config/mango/scripts/volmute.sh
#media
bind=NONE,XF86AudioPlay,spawn_shell,playerctl play-pause
bind=NONE,XF86AudioNext,spawn_shell,playerctl next
bind=NONE,XF86AudioPrev,spawn_shell,playerctl previous
#brightness
bind=NONE,XF86MonBrightnessUp,spawn_shell,~/.config/mango/scripts/brightup.sh
bind=NONE,XF86MonBrightnessDown,spawn_shell,~/.config/mango/scripts/brightdown.sh

bind=NONE,XF86Search,spawn_shell,~/.config/mango/scripts/powerprofile.sh

#screenshot
bind=NONE,Print,spawn_shell,~/.config/mango/scripts/fscreen.sh
bind=SHIFT,Print,spawn_shell,~/.config/mango/scripts/sscreen.sh
bind=Ctrl,Print,spawn_shell,~/.config/mango/scripts/toggle-recording.sh
bind=Ctrl+Shift,Print,spawn_shell,~/.config/mango/scripts/toggle-recording-area.sh

bind=SUPER,v,spawn,foot -e nvim
bind=SUPER,e,spawn,foot -e yazi
bind=SUPER,b,spawn,qutebrowser
bind=SUPER,t,spawn,foot

