# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x9081ceff
rootcolor = 0x151129ff
bordercolor = 0x6756a3ff
dropcolor = 0x9081ce80
splitcolor = 0x4f4289ff
focuscolor = 0x9081ceff
maximizescreencolor = 0x635b8dff
urgentcolor = 0xd4687bff
scratchpadcolor = 0x4f4289ff
globalcolor = 0x32207cff
overlaycolor = 0x1d1834ff
