# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0xe0858dff
rootcolor = 0x0f0a0bff
bordercolor = 0x795457ff
dropcolor = 0xe0858d80
splitcolor = 0xe6a0a8ff
focuscolor = 0xe0858dff
maximizescreencolor = 0xd96a76ff
urgentcolor = 0xd96a76ff
scratchpadcolor = 0xe6a0a8ff
globalcolor = 0x9c1722ff
overlaycolor = 0x7e131eff
