# change indexing to more human redable 
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
# colors config
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
#clipboard
set -g set-clipboard on
#enable status bar 
set -g status "on"
#status bar config
set -g status-justify "left"
set-option -g status-position top
