thm_bg="#1a1d20"
thm_fg="#2d3339"
thm_cyan="#c5baaf"
thm_black="#1a1d20"
thm_gray="#ebcfb2"
thm_magenta="#d5aca9"
thm_pink="#e2c3c1"
thm_red="#b38d97"
thm_green="#d5aca9"
thm_yellow="#ebcfb2"
thm_blue="#97a7b5"
thm_orange="#f3dfca"
thm_black4="#424b54"

set -g status-bg "${thm_bg}"
set -g message-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g message-command-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-current-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_magenta},bg=${thm_bg}](✓) #[fg=${thm_cyan},bg=${thm_bg}]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=${thm_magenta},bg=${thm_bg}]"
set -g window-status-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_fg},bg=${thm_bg}]#W"
set -g status-right "#[fg=${thm_blue},bg=${thm_bg},nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_blue},nobold,nounderscore,noitalics] #[fg=${thm_fg},bg=${thm_gray}] #W #{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_cyan}]}#[bg=${thm_gray}]#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_cyan}]}#[fg=${thm_bg}] #[fg=${thm_fg},bg=${thm_gray}] #S "
set -g status-left ""
set -g clock-mode-colour "${thm_blue}"
set -g mode-style "fg=${thm_blue} bg=${thm_black4} bold"

