thm_bg="#1a1b26"
thm_fg="#24283b"
thm_cyan="#7dcfff"
thm_black="#15161e"
thm_gray="#a9b1d6"
thm_magenta="#bb9af7"
thm_pink="#bb9af7"
thm_red="#f7768e"
thm_green="#9ece6a"
thm_yellow="#e0af68"
thm_blue="#7aa2f7"
thm_orange="#e0af68"
thm_black4="#414868"

set -g status-bg "${thm_bg}"
set -g message-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g message-command-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-current-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_magenta},bg=${thm_bg}](✓) #[fg=${thm_cyan},bg=${thm_bg}]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #[fg=${thm_magenta},bg=${thm_bg}]"
set -g window-status-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_fg},bg=${thm_bg}]#W"
set -g status-right "#[fg=${thm_blue},bg=${thm_bg},nobold,nounderscore,noitalics]#[fg=${thm_bg},bg=${thm_blue},nobold,nounderscore,noitalics] #[fg=${thm_fg},bg=${thm_gray}] #W #{?client_prefix,#[fg=${thm_magenta}],#[fg=${thm_cyan}]}#[bg=${thm_gray}]#{?client_prefix,#[bg=${thm_magenta}],#[bg=${thm_cyan}]}#[fg=${thm_bg}] #[fg=${thm_fg},bg=${thm_gray}] #S "
set -g status-left ""
set -g clock-mode-colour "${thm_blue}"
set -g mode-style "fg=${thm_blue} bg=${thm_black4} bold"

