[colors]
ansi = [
    "#0f0a0b",
    "#e67e8a",
    "#d96a76",
    "#e0858d",
    "#b55660",
    "#c95d68",
    "#d96a76",
    "#e6a0a8",
]
background = "#0f0a0b"
brights = [
    "#3d2a2c",
    "#ef97a0",
    "#e67e8a",
    "#f0a6ae",
    "#c96a74",
    "#d97b85",
    "#ef97a0",
    "#f2b8be",
]
compose_cursor = "#e0858d"
cursor_bg = "#e0858d"
cursor_border = "#e0858d"
cursor_fg = "#160a0b"
foreground = "#e6a0a8"
scrollbar_thumb = "#3d2a2c"
selection_bg = "#3d2a2c"
selection_fg = "#f0a6ae"
split = "#3d2a2c"
visual_bell = "#0f0a0b"

[colors.indexed]
16 = "#d96a76"
17 = "#e0858d"

[colors.tab_bar]
background = "#0f0a0b"
inactive_tab_edge = "#3d2a2c"

[colors.tab_bar.active_tab]
bg_color = "#e0858d"
fg_color = "#160a0b"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#0f0a0b"
fg_color = "#e6a0a8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#0f0a0b"
fg_color = "#e6a0a8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#3d2a2c"
fg_color = "#e6a0a8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#3d2a2c"
fg_color = "#e6a0a8"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "Noctalia"
name = "Noctalia"
